
version: "3.3"
services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    volumes:
      - /opt/npm:/data
      - /opt/npm/letsencrypt:/etc/letsencrypt
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
  uptime-kuma:
    restart: always
    volumes:
      - /opt/uptimekuma:/app/data
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - SERVERURL=vps.seandion.com
      - SERVERPORT=51820
      - SERVER_ALLOWEDIPS_PEER_1=10.0.0.0/8
      - PEERS=3
      - INTERNAL_SUBNET=10.253.100.0
    volumes:
      - /opt/wireguard:/config
    ports:
      - 51820:51820/udp
      - 443:443
      - 80:80
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
     # - net.ipv4.ip_forward=1
    networks:
      - proxynet
  portainer:
    restart: unless-stopped
    container_name: portainer
    image: portainer/portainer:latest
    environment:
      - TZ=America/Chicago
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
    networks:
      - proxynet
networks:
  proxynet:
